"""Generate interfaces/hexapod.urdf from the single source-of-truth geometry
in ShiriStern/wave-walk/config.py.

Why: Embedded needs a robot description to map servos to joints, and sim must
not drift from firmware. config.py is the ONE geometry file (its words); this
script emits a standard URDF from it so both worlds read the same numbers.

Run from repo root:  python interfaces/gen_urdf.py
"""
import math
import os
import sys

# import the canonical geometry
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ShiriStern", "wave-walk"))
import config as C  # noqa: E402

COXA_LO, COXA_HI = C.COXA_RANGE
FEMUR_LO, FEMUR_HI = C.FEMUR_RANGE
TIBIA_LO, TIBIA_HI = C.TIBIA_RANGE

# crude mass split of the per-leg mass; tune against real AX-12/MG90S later
LEG_MASS = 0.05  # kg per leg segment group (placeholder, documented as such)


def link(name, length, radius, mass):
    ixx = iyy = (1 / 12) * mass * (3 * radius**2 + length**2)
    izz = 0.5 * mass * radius**2
    return f"""  <link name="{name}">
    <visual>
      <origin xyz="{length/2:.4f} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="{length:.4f}" radius="{radius:.4f}"/></geometry>
    </visual>
    <collision>
      <origin xyz="{length/2:.4f} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="{length:.4f}" radius="{radius:.4f}"/></geometry>
    </collision>
    <inertial>
      <mass value="{mass:.4f}"/>
      <inertia ixx="{ixx:.6f}" ixy="0" ixz="0" iyy="{iyy:.6f}" iyz="0" izz="{izz:.6f}"/>
    </inertial>
  </link>"""


def joint(name, jtype, parent, child, xyz, rpy, axis, lo, hi):
    return f"""  <joint name="{name}" type="{jtype}">
    <parent link="{parent}"/>
    <child link="{child}"/>
    <origin xyz="{xyz}" rpy="{rpy}"/>
    <axis xyz="{axis}"/>
    <limit lower="{lo:.4f}" upper="{hi:.4f}" effort="3.0" velocity="6.0"/>
  </joint>"""


def build():
    out = []
    out.append('<?xml version="1.0"?>')
    out.append('<!-- GENERATED by interfaces/gen_urdf.py from ShiriStern/wave-walk/config.py -->')
    out.append('<!-- Frame: +X forward, +Y left, +Z up. Units: metres, radians. -->')
    out.append('<robot name="robo_greeno_hexapod">')

    # trunk
    out.append(f"""  <link name="base_link">
    <visual>
      <geometry><cylinder length="{2*C.BODY_HALF_H:.4f}" radius="{C.BODY_RADIUS:.4f}"/></geometry>
    </visual>
    <collision>
      <geometry><cylinder length="{2*C.BODY_HALF_H:.4f}" radius="{C.BODY_RADIUS:.4f}"/></geometry>
    </collision>
    <inertial>
      <mass value="{C.TRUNK_MASS:.4f}"/>
      <inertia ixx="0.0020" ixy="0" ixz="0" iyy="0.0020" iyz="0" izz="0.0035"/>
    </inertial>
  </link>""")

    # legs — order defines servo channels 0..17 (leg*3 + {coxa,femur,tibia})
    for leg_idx, (name, ang) in enumerate(C.LEGS):
        x = C.BODY_RADIUS * math.cos(ang)
        y = C.BODY_RADIUS * math.sin(ang)
        coxa_link = f"{name}_coxa_link"
        femur_link = f"{name}_femur_link"
        tibia_link = f"{name}_tibia_link"

        # coxa: yaw hinge about +Z, mounted at the body rim, rotated by mount angle
        out.append(joint(f"{name}_coxa", "revolute", "base_link", coxa_link,
                         f"{x:.4f} {y:.4f} 0", f"0 0 {ang:.4f}", "0 0 1", COXA_LO, COXA_HI))
        out.append(link(coxa_link, C.COXA, 0.012, LEG_MASS))

        # femur: lift hinge about local +Y, at the end of the coxa link
        out.append(joint(f"{name}_femur", "revolute", coxa_link, femur_link,
                         f"{C.COXA:.4f} 0 0", "0 0 0", "0 1 0", FEMUR_LO, FEMUR_HI))
        out.append(link(femur_link, C.FEMUR, 0.011, LEG_MASS))

        # tibia: lift hinge about local +Y, at the end of the femur link
        out.append(joint(f"{name}_tibia", "revolute", femur_link, tibia_link,
                         f"{C.FEMUR:.4f} 0 0", "0 0 0", "0 1 0", TIBIA_LO, TIBIA_HI))
        out.append(link(tibia_link, C.TIBIA, 0.010, LEG_MASS))

        # foot tip frame at the end of the tibia (for IK targets / contact)
        out.append(f"""  <link name="{name}_foot"/>
  <joint name="{name}_foot_fixed" type="fixed">
    <parent link="{tibia_link}"/>
    <child link="{name}_foot"/>
    <origin xyz="{C.TIBIA:.4f} 0 0" rpy="0 0 0"/>
  </joint>""")

    out.append("</robot>")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    urdf = build()
    dst = os.path.join(os.path.dirname(__file__), "hexapod.urdf")
    with open(dst, "w") as f:
        f.write(urdf)
    njoints = 3 * len(C.LEGS)
    print(f"wrote {dst}: {len(C.LEGS)} legs, {njoints} actuated joints")
